# Generated by Django 6.0.5 on 2026-05-18 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bid_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bid',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'buyer',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'db_table': 'category',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('active', 'Active'), ('sold', 'Sold'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lot',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LotCategory',
            fields=[
                ('pk', models.CompositePrimaryKey('lot', 'category', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'lot_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'operator',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'seller',
                'ordering': ['id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellerVerification',
            fields=[
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='verification', serialize=False, to='academics.seller')),
                ('passport_number', models.CharField(max_length=20)),
                ('tax_id', models.CharField(max_length=20)),
                ('is_verified', models.BooleanField(blank=True, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seller_verification',
                'managed': False,
            },
        ),
    ]
